### PR TITLE
Update to 0.15

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Crashes on:
```

----- Client Initialization Complete -----
----- R_Init -----
SDL using driver "x11"
Initializing OpenGL display
Display aspect: 1.778
...setting mode 1920x1080
Trying to get an OpenGL 3.2 core context
SDL_GL_CreateContext succeeded.
Using 24 color bits, 24 depth, 8 stencil display.
Available modes: '0x0 864x486 1024x576 1280x720 1600x900 1920x1080 1368x768 720x400 640x350 320x200 640x400 1280x800 1440x900 1680x1050 720x480 320x240 640x480 800x600 1024x768 1152x864 1280x960 1400x1050 1440x1080 1280x1024'
tty]double free or corruption (!prev)
----- Client Shutdown (Received signal 6) -----
tty]

```

@dGr8LookinSparky Any idea?

**Comment by cengique** [comment]
@AsciiWolf this is strange. I have not seen this error. We may need to debug a bit more.

**Comment by cengique** [comment]
@Buom01 do you have any insights into whether your changes in merge https://github.com/GrangerHub/tremulous/commit/500043fb632042d848845321e62520b2ef2f78a6 can cause this?

**Comment by AsciiWolf** [comment]
bot, build

**Comment by Buom01** [comment]
Particular steps to reproduce ?
I'm able to run the game after `flatpak install --user https://dl.flathub.org/build-repo/25149/com.grangerhub.Tremulous.flatpakref` and connect to different servers

**Comment by Buom01** [comment]
https://pastebin.com/ytfhXn7W

Note: Flatpak said it's already installed. I have installed it tonight as it weren't, so it's fresh.

> By the way, I have also noticed that renderer_opengl1.so is used instead of renderer_opengl2.so in the new build. Is this intended?
I remember I have set OpenGL 2 by default at a moment, but probably it weren't stable enough to let it go. However, it can be configured easily in the menu.

Your console talk about OpenGL 3.2, I haven't that on mine.

**Comment by AsciiWolf** [comment]
The OpenGL 3.2 line is also caused by using the old config (with renderer_opengl2.so) from previous Tremulous version. Feel free to ignore it.

This is how it looks like after (re)moving the _~/.var/app/com.grangerhub.Tremulous_ directory to force new config file generation:

screenshot3

**Comment by cengique** [comment]
@AsciiWolf I'm trying to test this, but I'm getting a 404 for the above command:

```
$ flatpak install --user https://dl.flathub.org/build-repo/25149/com.grangerhub.Tremulous.flatpakref

error: Can't load uri https://dl.flathub.org/build-repo/25149/com.grangerhub.Tremulous.flatpakref: Server returned status 404
```

**Comment by AsciiWolf** [comment]
The test build is kept in the build-repo for only a few days. I will trigger a new build.

bot, build

**Comment by cengique** [comment]
> The test build is kept in the build-repo for only a few days. I will trigger a new build.

Thank you @AsciiWolf ! I can confirm that on my system it also works without the "double free or corruption" error. However, I get no sound in either stable or test branches. It must be a problem with my flatpak setup.

I heard from someone that 0.15 had a problem with using an existing home path. So I tried by setting the homepath to a new, empty folder:

```
flatpak run --branch=test com.grangerhub.Tremulous +set fs_homepath ~/.tremulous-test2/
```

It still worked for me. @AsciiWolf please try with the empty homepath and also do you have another system you can try this on? I am testing on a Linux x86_64 system. Even though Flatpak is there to avoid this, could it be a system-specific issue?

**Comment by AsciiWolf** [comment]
I have already tried it with empty homepath - same issue.

I will try the test build on my second PC (work laptop with Intel GPU) tomorrow. :-)

**Comment by AsciiWolf** [comment]
Interesting, it runs fine on my second computer with Intel GPU (except for some [graphical glitches](https://github.com/flathub/com.grangerhub.Tremulous/assets/2339930/3556cf37-4e00-4edf-93a9-8239eaa35d73)).

However, when I switched the renderer to opengl2 and tried connecting to some online server, it also crashed on `double free or corruption (!prev)`. But local server still worked fine. Strange. Maybe the online server had a different QVM that triggered the issue.

**Pull request merged**
