### PR TITLE
Update the runtime

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
@dGr8LookinSparky Do you have any idea what could be causing this issue? The C++ standard used by GCC 10 (fd 20.08 runtime) and older GCC 9 (fd 19.08 runtime) seems to be the same.

**Comment by AsciiWolf** [comment]
@Buom01 Maybe you have any idea how to fix the issue? :-)

**Comment by AsciiWolf** [comment]
@Buom01 @nedrichards @barthalion Maybe you have any idea how to fix the issue? :-)

**Comment by AsciiWolf** [comment]
[Here](https://github.com/GrangerHub/tremulous/blob/master/external/sol/sol.hpp) is the sol.hpp source code.

**Comment by Buom01** [comment]
GCC-9 !

**Comment by AsciiWolf** [comment]
Thanks for the comment! The problem is that, as far as I know, it is not possible to change the gcc version included in the Flatpak runtime SDK. :-/

So, either sol.hpp will have to be patched to compile on gcc10 or Tremulous will keep using the older runtime.

**Comment by barthalion** [comment]
I guess that updating sol version used by the game would help? https://github.com/ThePhD/sol2

**Comment by AsciiWolf** [comment]
I have already tried updating the sol version, however the latest code seems to be completely different than the currently used version (from 2016) and I was not able to compile it with Tremulous. :-/

**Comment by barthalion** [comment]
Does this commit make any sense in the context of Tremulous's sol? https://github.com/ThePhD/sol2/commit/275ae2c096247097ba0ba03c773f079cbd02f1f8

**Comment by AsciiWolf** [comment]
Thanks!

This is the problematic code:
https://github.com/GrangerHub/tremulous/blob/master/external/sol/sol.hpp#L6515
https://github.com/GrangerHub/tremulous/blob/master/external/sol/sol.hpp#L6526
https://github.com/GrangerHub/tremulous/blob/master/external/sol/sol.hpp#L6537

And this part of the PR changes the same code:
https://github.com/ThePhD/sol2/commit/275ae2c096247097ba0ba03c773f079cbd02f1f8#diff-004413a113e22fb989eb6b9e8c413ea420e6cc4ed244c8db7eac92b2d14914dcL14321

Hmm, this could work, I'll try it. Thanks! :-)

**Pull request merged**
